import type { PRCard } from "@review365/api/types";

// PROTOTYPE fixture — throwaway, not real data. 8 cards across 3 repos,
// interleaved in "arrival order" so the ungrouped baseline looks like a real
// watchlist feed rather than pre-sorted mock data.

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();

export const FAKE_CARDS: PRCard[] = [
  {
    id: "pr_narze_review365_142",
    platform: "github",
    prNumber: 142,
    repo: "narze/review365",
    title: "Add group-by-repo toggle to column options",
    author: "narze",
    url: "https://github.com/narze/review365/pull/142",
    updatedAt: hoursAgo(2),
    isOwnPR: false,
    columnId: "inbox",
    signals: ["review-requested"],
    archived: false,
    order: 0,
  },
  {
    id: "pr_acme_api-gateway_58",
    platform: "github",
    prNumber: 58,
    repo: "acme/api-gateway",
    title: "Retry transient 502s on the token exchange",
    author: "delacruz",
    url: "https://github.com/acme/api-gateway/pull/58",
    updatedAt: hoursAgo(5),
    isOwnPR: false,
    columnId: "inbox",
    signals: ["review-requested"],
    archived: false,
    order: 1,
  },
  {
    id: "pr_narze_review365_139",
    platform: "github",
    prNumber: 139,
    repo: "narze/review365",
    title: "Fix flaky keyboard navigation test",
    author: "aji",
    url: "https://github.com/narze/review365/pull/139",
    updatedAt: hoursAgo(30),
    isOwnPR: false,
    columnId: "inbox",
    signals: ["changes-requested"],
    archived: false,
    order: 2,
  },
  {
    id: "pr_acme_design-system_21",
    platform: "github",
    prNumber: 21,
    repo: "acme/design-system",
    title: "Update button focus ring tokens",
    author: "priya",
    url: "https://github.com/acme/design-system/pull/21",
    updatedAt: hoursAgo(9),
    isOwnPR: false,
    columnId: "inbox",
    signals: ["review-requested"],
    archived: false,
    order: 3,
  },
  {
    id: "pr_acme_api-gateway_55",
    platform: "github",
    prNumber: 55,
    repo: "acme/api-gateway",
    title: "Add per-route rate limiting",
    author: "delacruz",
    url: "https://github.com/acme/api-gateway/pull/55",
    updatedAt: hoursAgo(48),
    isOwnPR: false,
    columnId: "inbox",
    signals: ["approved"],
    archived: false,
    order: 4,
  },
  {
    id: "pr_narze_review365_146",
    platform: "github",
    prNumber: 146,
    repo: "narze/review365",
    title: "Copy column list should respect the archived toggle",
    author: "narze",
    url: "https://github.com/narze/review365/pull/146",
    updatedAt: hoursAgo(1),
    isOwnPR: false,
    columnId: "inbox",
    signals: ["draft"],
    archived: false,
    order: 5,
  },
  {
    id: "pr_acme_api-gateway_60",
    platform: "github",
    prNumber: 60,
    repo: "acme/api-gateway",
    title: "Migrate health check to /healthz",
    author: "oduya",
    url: "https://github.com/acme/api-gateway/pull/60",
    updatedAt: hoursAgo(75),
    isOwnPR: false,
    columnId: "inbox",
    signals: ["review-requested"],
    archived: false,
    order: 6,
  },
  {
    id: "pr_narze_review365_150",
    platform: "github",
    prNumber: 150,
    repo: "narze/review365",
    title: "Prototype: three variants for column grouping",
    author: "narze",
    url: "https://github.com/narze/review365/pull/150",
    updatedAt: hoursAgo(0.2),
    isOwnPR: true,
    columnId: "inbox",
    signals: ["own-pr", "pr-open"],
    archived: false,
    order: 7,
  },
];
